server:
  port: 4006
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

api:
  prefix: /api/v1

spring:
  application:
    name: shoppe-be

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://zimacube:5432/shoppe}
    username: ${SPRING_DATASOURCE_USERNAME:shoppe}
    password: ${SPRING_DATASOURCE_PASSWORD:shoppe}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: i18n/messages
    encoding: UTF-8

  cloud:
    discovery:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://zimacube:9080/realms/shoppe
#          jwk-set-uri: http://zimacube:9080/realms/shoppe/protocol/openid-connect/certs

# Keycloak configuration
keycloak:
  url: http://zimacube:9080/realms/shoppe/protocol/openid-connect/token
  server-url: http://localhost:9099
  realm: shoppe
  client-id: shoppe-be
  grant-type: password
  password: genedu-admin
  username: genedu-admin
  client-secret: ${KC_GENEDU_ADMIN_CLI_GENEDU_SCRET_KEY:MFV2Vqin54jV8YogelZgxjJFvRiYVRiS}

jwt:
  auth:
    converter:
      resource-id: react-app
      principal-attribute: preferred_username
  expiration: ${JWT_EXPIRATION:2592000}
  expiration-refresh-token: ${JWT_EXPIRATION_REFRESH_TOKEN:5184000}
  secretKey: ${JWT_SECRET_KEY:TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=}

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    springframework.security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.redis: DEBUG
    javax.management: off
    sun.rmi: off
    sun.rmi.transport.tcp: off
    sun.rmi.loader: off