--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

-- Started on 2025-08-01 09:50:15 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 18625)
-- Name: addresses; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.addresses (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    address_line character varying(255),
    city character varying(255),
    district character varying(255),
    is_default boolean,
    phone character varying(255),
    postal_code character varying(255),
    recipient_name character varying(255),
    user_id integer NOT NULL
);


ALTER TABLE public.addresses OWNER TO admin;

--
-- TOC entry 215 (class 1259 OID 18624)
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 18635)
-- Name: admin_settings; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.admin_settings (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    description character varying(255),
    setting_key character varying(255),
    setting_value character varying(255)
);


ALTER TABLE public.admin_settings OWNER TO admin;

--
-- TOC entry 217 (class 1259 OID 18634)
-- Name: admin_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.admin_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 18645)
-- Name: api_quotas; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.api_quotas (
    id bigint NOT NULL,
    api_endpoint character varying(255),
    max_requests integer NOT NULL,
    request_count integer NOT NULL,
    reset_time timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.api_quotas OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 18644)
-- Name: api_quotas_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.api_quotas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_quotas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 18651)
-- Name: cart_items; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    cart_id bigint NOT NULL,
    price_at_time double precision NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE public.cart_items OWNER TO admin;

--
-- TOC entry 221 (class 1259 OID 18650)
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 18657)
-- Name: carts; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.carts (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.carts OWNER TO admin;

--
-- TOC entry 223 (class 1259 OID 18656)
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 18667)
-- Name: categories; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active boolean NOT NULL,
    description character varying(255),
    image_url character varying(255),
    name character varying(255),
    parent_id bigint,
    slug character varying(255)
);


ALTER TABLE public.categories OWNER TO admin;

--
-- TOC entry 225 (class 1259 OID 18666)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 18677)
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.chat_messages (
    id integer NOT NULL,
    is_read boolean NOT NULL,
    message character varying(255),
    receiver_id integer NOT NULL,
    sender_id integer NOT NULL,
    sent_at bytea
);


ALTER TABLE public.chat_messages OWNER TO admin;

--
-- TOC entry 227 (class 1259 OID 18676)
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 18685)
-- Name: coupons; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.coupons (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active boolean NOT NULL,
    code character varying(255),
    discount_percent double precision,
    expiry_date timestamp(6) without time zone,
    usage_limit double precision,
    valid_from timestamp(6) without time zone,
    valid_to timestamp(6) without time zone
);


ALTER TABLE public.coupons OWNER TO admin;

--
-- TOC entry 229 (class 1259 OID 18684)
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 18695)
-- Name: currency_rates; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.currency_rates (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    from_currency character varying(255) NOT NULL,
    rate numeric(38,2) NOT NULL,
    to_currency character varying(255) NOT NULL,
    CONSTRAINT currency_rates_from_currency_check CHECK (((from_currency)::text = ANY ((ARRAY['USD'::character varying, 'VND'::character varying, 'JPY'::character varying])::text[]))),
    CONSTRAINT currency_rates_to_currency_check CHECK (((to_currency)::text = ANY ((ARRAY['USD'::character varying, 'VND'::character varying, 'JPY'::character varying])::text[])))
);


ALTER TABLE public.currency_rates OWNER TO admin;

--
-- TOC entry 231 (class 1259 OID 18694)
-- Name: currency_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.currency_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 18707)
-- Name: login_history; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.login_history (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip_address character varying(100),
    location character varying(100),
    login_at timestamp(6) without time zone NOT NULL,
    success boolean NOT NULL,
    user_agent character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.login_history OWNER TO admin;

--
-- TOC entry 233 (class 1259 OID 18706)
-- Name: login_history_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.login_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 18717)
-- Name: notifications; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    description text NOT NULL,
    email character varying(255) NOT NULL,
    icon_color_hex character varying(255),
    icon_name character varying(255),
    is_read boolean DEFAULT false,
    "time" timestamp(6) without time zone NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255),
    CONSTRAINT notifications_icon_color_hex_check CHECK (((icon_color_hex)::text = ANY ((ARRAY['BLUE'::character varying, 'YELLOW'::character varying, 'GREEN'::character varying, 'RED'::character varying])::text[]))),
    CONSTRAINT notifications_icon_name_check CHECK (((icon_name)::text = ANY ((ARRAY['MESSAGE'::character varying, 'ALERT'::character varying, 'CHECK'::character varying, 'ERROR'::character varying])::text[]))),
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['INFO'::character varying, 'WARNING'::character varying, 'SUCCESS'::character varying, 'ERROR'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO admin;

--
-- TOC entry 235 (class 1259 OID 18716)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 18730)
-- Name: order_items; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_image character varying(255),
    product_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    total_price double precision NOT NULL,
    unit_price double precision NOT NULL
);


ALTER TABLE public.order_items OWNER TO admin;

--
-- TOC entry 276 (class 1259 OID 18959)
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.order_items_id_seq OWNER TO admin;

--
-- TOC entry 239 (class 1259 OID 18738)
-- Name: order_status_logs; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.order_status_logs (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    order_id integer,
    status integer
);


ALTER TABLE public.order_status_logs OWNER TO admin;

--
-- TOC entry 238 (class 1259 OID 18737)
-- Name: order_status_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.order_status_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_status_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 18748)
-- Name: orders; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    address_id bigint,
    coupon_id bigint,
    delivered_at timestamp(6) without time zone,
    discount_amount double precision,
    estimated_delivery timestamp(6) without time zone,
    notes text,
    order_number character varying(255) NOT NULL,
    payment_status character varying(255),
    shipping_fee double precision,
    shipping_method_id bigint,
    shipping_status character varying(255),
    status character varying(255) NOT NULL,
    subtotal double precision NOT NULL,
    tax_amount double precision,
    total_amount double precision NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT orders_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'PARTIAL_REFUND'::character varying])::text[]))),
    CONSTRAINT orders_shipping_status_check CHECK (((shipping_status)::text = ANY ((ARRAY['NOT_SHIPPED'::character varying, 'PREPARING'::character varying, 'SHIPPED'::character varying, 'IN_TRANSIT'::character varying, 'OUT_FOR_DELIVERY'::character varying, 'DELIVERED'::character varying, 'RETURNED'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying, 'RETURNED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO admin;

--
-- TOC entry 240 (class 1259 OID 18747)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 18761)
-- Name: otps; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.otps (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email character varying(255),
    expired_at timestamp(6) without time zone NOT NULL,
    is_expired boolean,
    is_used boolean,
    otp character varying(255)
);


ALTER TABLE public.otps OWNER TO admin;

--
-- TOC entry 242 (class 1259 OID 18760)
-- Name: otps_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.otps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 18771)
-- Name: payments; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    amount double precision NOT NULL,
    description character varying(255),
    order_id bigint NOT NULL,
    paid boolean,
    paid_at integer,
    payment_method smallint,
    payment_method_id integer,
    status smallint,
    transaction_id character varying(255),
    CONSTRAINT payments_payment_method_check CHECK (((payment_method >= 0) AND (payment_method <= 4))),
    CONSTRAINT payments_status_check CHECK (((status >= 0) AND (status <= 4)))
);


ALTER TABLE public.payments OWNER TO admin;

--
-- TOC entry 244 (class 1259 OID 18770)
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 18783)
-- Name: product_images; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.product_images (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    image_url character varying(255),
    is_primary boolean NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.product_images OWNER TO admin;

--
-- TOC entry 246 (class 1259 OID 18782)
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 18793)
-- Name: product_reviews; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.product_reviews (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    comment character varying(255),
    product_id integer NOT NULL,
    rating integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.product_reviews OWNER TO admin;

--
-- TOC entry 248 (class 1259 OID 18792)
-- Name: product_reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.product_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 18803)
-- Name: product_variants; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.product_variants (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    price_adjustment character varying(255),
    product_id integer NOT NULL,
    stock integer NOT NULL,
    variant_name character varying(255)
);


ALTER TABLE public.product_variants OWNER TO admin;

--
-- TOC entry 250 (class 1259 OID 18802)
-- Name: product_variants_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.product_variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_variants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 18813)
-- Name: products; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active boolean,
    category_id bigint NOT NULL,
    description text,
    dimensions character varying(255),
    featured boolean,
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    rating double precision,
    review_count integer,
    shop_id bigint NOT NULL,
    sku character varying(255),
    sold_count integer,
    status character varying(255),
    stock integer NOT NULL,
    weight double precision,
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'OUT_OF_STOCK'::character varying, 'DISCONTINUED'::character varying])::text[])))
);


ALTER TABLE public.products OWNER TO admin;

--
-- TOC entry 252 (class 1259 OID 18812)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 18824)
-- Name: shipping_methods; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.shipping_methods (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active boolean NOT NULL,
    cost double precision,
    estimated_days integer NOT NULL,
    name character varying(255)
);


ALTER TABLE public.shipping_methods OWNER TO admin;

--
-- TOC entry 254 (class 1259 OID 18823)
-- Name: shipping_methods_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.shipping_methods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipping_methods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 18834)
-- Name: shop_notifications; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.shop_notifications (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    content character varying(255),
    is_read boolean NOT NULL,
    shop_id integer,
    type integer
);


ALTER TABLE public.shop_notifications OWNER TO admin;

--
-- TOC entry 256 (class 1259 OID 18833)
-- Name: shop_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.shop_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 18843)
-- Name: social_accounts; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.social_accounts (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email character varying(150),
    name character varying(255),
    provider_name smallint,
    user_id bigint,
    CONSTRAINT social_accounts_provider_name_check CHECK (((provider_name >= 0) AND (provider_name <= 1)))
);


ALTER TABLE public.social_accounts OWNER TO admin;

--
-- TOC entry 277 (class 1259 OID 18960)
-- Name: social_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.social_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.social_accounts_id_seq OWNER TO admin;

--
-- TOC entry 259 (class 1259 OID 18853)
-- Name: token; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.token (
    id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expiration_date timestamp(6) without time zone,
    expired boolean NOT NULL,
    is_mobile boolean NOT NULL,
    refresh_expiration_date timestamp(6) without time zone,
    refresh_token character varying(255),
    revoked boolean NOT NULL,
    token character varying(255),
    token_type character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.token OWNER TO admin;

--
-- TOC entry 261 (class 1259 OID 18863)
-- Name: user_addresses; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_addresses (
    id bigint NOT NULL,
    address character varying(255),
    is_default boolean NOT NULL,
    name_of_user character varying(255),
    phone_number character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.user_addresses OWNER TO admin;

--
-- TOC entry 260 (class 1259 OID 18862)
-- Name: user_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 18871)
-- Name: user_device_tokens; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_device_tokens (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    device_id character varying(255) NOT NULL,
    device_name character varying(255),
    email character varying(255) NOT NULL,
    fcm_token character varying(512) NOT NULL,
    platform character varying(255)
);


ALTER TABLE public.user_device_tokens OWNER TO admin;

--
-- TOC entry 262 (class 1259 OID 18870)
-- Name: user_device_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_device_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_device_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 18881)
-- Name: user_notifications; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_notifications (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    content character varying(255),
    is_read boolean NOT NULL,
    type integer,
    user_id integer
);


ALTER TABLE public.user_notifications OWNER TO admin;

--
-- TOC entry 264 (class 1259 OID 18880)
-- Name: user_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 18891)
-- Name: user_settings; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_settings (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    dark_mode boolean,
    login_alerts boolean,
    email_master_enabled boolean,
    email_order boolean,
    email_promo boolean,
    email_survey boolean,
    sms_master_enabled boolean,
    sms_promo boolean,
    zalo_master_enabled boolean,
    zalo_promo boolean,
    request_disable_account boolean,
    two_fa_enabled boolean,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_settings OWNER TO admin;

--
-- TOC entry 266 (class 1259 OID 18890)
-- Name: user_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 18901)
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    avatar character varying(255),
    cart_id character varying(255),
    date_of_birth character varying(255),
    email character varying(255),
    gender smallint,
    password character varying(255),
    name character varying(255),
    phone character varying(255),
    preferred_currency character varying(255) NOT NULL,
    preferred_language character varying(255) NOT NULL,
    role smallint,
    status smallint,
    totp_secret character varying(255),
    username character varying(255),
    wallet_id character varying(255),
    user_settings_id bigint,
    CONSTRAINT users_gender_check CHECK (((gender >= 0) AND (gender <= 2))),
    CONSTRAINT users_role_check CHECK (((role >= 0) AND (role <= 4))),
    CONSTRAINT users_status_check CHECK (((status >= 0) AND (status <= 3)))
);


ALTER TABLE public.users OWNER TO admin;

--
-- TOC entry 268 (class 1259 OID 18900)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 18914)
-- Name: wallet_transactions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.wallet_transactions (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    amount numeric(38,2) NOT NULL,
    completed_at timestamp(6) without time zone,
    currency character varying(255) NOT NULL,
    description character varying(255),
    reference_id character varying(255),
    status smallint NOT NULL,
    transaction_id character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    wallet_id bigint,
    CONSTRAINT wallet_transactions_status_check CHECK (((status >= 0) AND (status <= 3))),
    CONSTRAINT wallet_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying, 'PAYMENT'::character varying, 'REFUND'::character varying])::text[])))
);


ALTER TABLE public.wallet_transactions OWNER TO admin;

--
-- TOC entry 270 (class 1259 OID 18913)
-- Name: wallet_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.wallet_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 18926)
-- Name: wallets; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.wallets (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active boolean NOT NULL,
    balance numeric(38,2) NOT NULL,
    currency character varying(255) NOT NULL,
    wallet_id character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.wallets OWNER TO admin;

--
-- TOC entry 272 (class 1259 OID 18925)
-- Name: wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.wallets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 275 (class 1259 OID 18936)
-- Name: wishlists; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.wishlists (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(255),
    last_modified_by character varying(255),
    last_modified_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    product_id integer,
    user_id integer
);


ALTER TABLE public.wishlists OWNER TO admin;

--
-- TOC entry 274 (class 1259 OID 18935)
-- Name: wishlists_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.wishlists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3729 (class 0 OID 18625)
-- Dependencies: 216
-- Data for Name: addresses; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.addresses (id, created_at, created_by, last_modified_by, last_modified_on, address_line, city, district, is_default, phone, postal_code, recipient_name, user_id) FROM stdin;
\.


--
-- TOC entry 3731 (class 0 OID 18635)
-- Dependencies: 218
-- Data for Name: admin_settings; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.admin_settings (id, created_at, created_by, last_modified_by, last_modified_on, description, setting_key, setting_value) FROM stdin;
1	2025-08-01 16:17:23.674369	\N	\N	2025-08-01 16:17:23.674377	Name of the e-commerce site	site.name	Shoppe
2	2025-08-01 16:17:23.676533	\N	\N	2025-08-01 16:17:23.676541	Description of the e-commerce site	site.description	An e-commerce platform
3	2025-08-01 16:17:23.67842	\N	\N	2025-08-01 16:17:23.678431	Contact email for the site	site.contact.email	contact@shoppe.com
4	2025-08-01 16:17:23.68048	\N	\N	2025-08-01 16:17:23.680488	Contact phone number for the site	site.contact.phone	+84123456789
5	2025-08-01 16:17:23.682447	\N	\N	2025-08-01 16:17:23.682459	Default currency for payments	payment.currency	USD
6	2025-08-01 16:17:23.684624	\N	\N	2025-08-01 16:17:23.684633	Available payment methods	payment.methods	Credit Card,PayPal,Bank Transfer
7	2025-08-01 16:17:23.686333	\N	\N	2025-08-01 16:17:23.686341	Automatically confirm orders after payment	order.auto_confirm	false
8	2025-08-01 16:17:23.689596	\N	\N	2025-08-01 16:17:23.689605	Enable user registration	user.registration.enabled	true
9	2025-08-01 16:17:23.692671	\N	\N	2025-08-01 16:17:23.692679	Require email verification for new users	user.verification.required	true
10	2025-08-01 16:17:23.694448	\N	\N	2025-08-01 16:17:23.694457	Enable maintenance mode for the site	maintenance.mode	false
11	2025-08-01 16:17:23.696395	\N	\N	2025-08-01 16:17:23.696404	Maximum file upload size in bytes	file.max_upload_size	10485760
\.


--
-- TOC entry 3733 (class 0 OID 18645)
-- Dependencies: 220
-- Data for Name: api_quotas; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.api_quotas (id, api_endpoint, max_requests, request_count, reset_time, user_id) FROM stdin;
\.


--
-- TOC entry 3735 (class 0 OID 18651)
-- Dependencies: 222
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.cart_items (id, cart_id, price_at_time, product_id, quantity) FROM stdin;
\.


--
-- TOC entry 3737 (class 0 OID 18657)
-- Dependencies: 224
-- Data for Name: carts; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.carts (id, created_at, created_by, last_modified_by, last_modified_on, user_id) FROM stdin;
\.


--
-- TOC entry 3739 (class 0 OID 18667)
-- Dependencies: 226
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.categories (id, created_at, created_by, last_modified_by, last_modified_on, active, description, image_url, name, parent_id, slug) FROM stdin;
18	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Thời Trang Trẻ Em	-1	\N
19	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Dụng Cụ và Thiết Bị Tiện Ích	-1	\N
20	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Sắc Đẹp	-1	\N
21	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Giày Dép Nam	-1	\N
22	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Bách Hóa Online	-1	\N
23	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Đồ Chơi	-1	\N
24	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Máy Ảnh & Máy Quay Phim	-1	\N
25	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Túi Ví Nữ	-1	\N
26	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Ô Tô & Xe Máy & Xe Đạp	-1	\N
27	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Giặt Giũ & Chăm Sóc Nhà Cửa	-1	\N
28	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Sức Khỏe	-1	\N
29	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Thiết Bị Điện Gia Dụng	-1	\N
30	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Nhà Sách Online	-1	\N
31	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Chăm Sóc Thú Cưng	-1	\N
32	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Voucher & Dịch Vụ	-1	\N
6	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Thời trang nam	-1	\N
7	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Thời trang nữ	-1	\N
8	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Điện thoại & Phụ Kiện	-1	\N
9	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Mẹ & Bé	-1	\N
10	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Thiết bị điện tử	-1	\N
11	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Nhà Cửa & Đời Sống	-1	\N
12	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Đồng Hồ	-1	\N
13	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Phụ Kiện & Trang Sức Nữ	-1	\N
14	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Balo & Túi Ví Nam	-1	\N
15	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Máy Tính & Laptop	-1	\N
16	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Giày Dép Nữ	-1	\N
17	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Thể Thao & Du Lịch	-1	\N
1	2025-08-01 16:17:22.501733	\N	\N	2025-08-01 16:17:22.501751	t	Electronic devices and accessories	https://example.com/images/electronics.jpg	Electronics	\N	electronics
2	2025-08-01 16:17:22.511382	\N	\N	2025-08-01 16:17:22.511394	t	Apparel and fashion items	https://example.com/images/clothing.jpg	Clothing	\N	clothing
3	2025-08-01 16:17:22.513701	\N	\N	2025-08-01 16:17:22.51371	t	Home appliances and kitchen essentials	https://example.com/images/home-kitchen.jpg	Home & Kitchen	\N	home-kitchen
4	2025-08-01 16:17:22.515487	\N	\N	2025-08-01 16:17:22.515498	t	Books, e-books, and publications	https://example.com/images/books.jpg	Books	\N	books
5	2025-08-01 16:17:22.517947	\N	\N	2025-08-01 16:17:22.517955	t	Beauty products and personal care items	https://example.com/images/beauty.jpg	Beauty & Personal Care	\N	beauty-personal-care
33	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Áo Khoác	1	\N
34	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Áo Vest và Blazer	1	\N
35	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Áo Hoodie, Áo Len & Áo Nỉ	1	\N
36	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Quần Jeans	1	\N
37	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Quần Dài/Quần Âu	1	\N
38	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Quần Short	1	\N
39	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Áo	1	\N
40	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Áo Ba Lỗ	1	\N
41	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Đồ Lót	1	\N
42	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Đồ Ngủ	1	\N
43	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Đồ Bộ	1	\N
44	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Vớ/Tất	1	\N
45	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Trang Phục Truyền Thống	1	\N
46	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Đồ Hóa Trang	1	\N
47	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Trang Phục Ngành Nghề	1	\N
48	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Khác	1	\N
49	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Trang Sức Nam	1	\N
50	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Kính Mắt Nam	1	\N
51	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Thắt Lưng Nam	1	\N
52	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Cà vạt & Nơ cổ	1	\N
53	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Phụ Kiện Nam	1	\N
54	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Quần	2	\N
55	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Quần đùi	2	\N
56	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Chân váy	2	\N
57	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Quần jeans	2	\N
58	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Đầm/Váy	2	\N
59	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Váy cưới	2	\N
60	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Đồ liền thân	2	\N
61	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Áo khoác, Áo choàng & Vest	2	\N
62	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Áo len & Cardigan	2	\N
63	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Hoodie và Áo nỉ	2	\N
64	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Bộ	2	\N
65	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Đồ lót	2	\N
66	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Đồ ngủ	2	\N
67	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Áo	2	\N
68	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Đồ tập	2	\N
69	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Đồ bầu	2	\N
70	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Đồ truyền thống	2	\N
71	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Đồ hóa trang	2	\N
72	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Vải	2	\N
73	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Vớ/ Tất	2	\N
74	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Khác	2	\N
75	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Điện thoại	3	\N
76	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Máy tính bảng	3	\N
77	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Pin Dự Phòng	3	\N
78	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Pin Gắn Trong, Cáp và Bộ Sạc	3	\N
79	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Ốp lưng, bao da, Miếng dán điện thoại	3	\N
80	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Bảo vệ màn hình	3	\N
81	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Đế giữ điện thoại	3	\N
82	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Thẻ nhớ	3	\N
83	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Sim	3	\N
84	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Phụ kiện khác	3	\N
85	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Thiết bị khác	3	\N
86	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Đồ dùng du lịch cho bé	4	\N
87	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Đồ dùng ăn dặm cho bé	4	\N
88	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Phụ kiện cho mẹ	4	\N
89	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Chăm sóc sức khỏe mẹ	4	\N
90	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Đồ dùng phòng tắm & Chăm sóc cơ thể bé	4	\N
91	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Đồ dùng phòng ngủ cho bé	4	\N
92	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	An toàn cho bé	4	\N
93	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Thực phẩm cho bé	4	\N
94	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Chăm sóc sức khỏe bé	4	\N
95	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Tã & bô em bé	4	\N
96	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Đồ chơi	4	\N
97	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Bộ & Gói quà tặng	4	\N
98	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Khác	4	\N
99	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Sữa công thức trên 24 tháng	4	\N
100	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Sữa công thức trên 0-24 tháng tuổi	4	\N
101	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Thiết bị đeo thông minh	5	\N
102	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Phụ kiện tivi	5	\N
103	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Máy Game Console	5	\N
104	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Phụ kiện Console	5	\N
105	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Đĩa game	5	\N
106	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Linh phụ kiện	5	\N
107	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Tai nghe nhét tai	5	\N
108	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Loa	5	\N
109	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Tivi	5	\N
110	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Tivi Box	5	\N
111	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Headphones	5	\N
112	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Chăn, Ga, Gối & Nệm	6	\N
113	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Trang trí nhà cửa	6	\N
114	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Dụng cụ & Thiết bị tiện ích	6	\N
115	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Đồ dùng nhà bếp và hộp đựng thực phẩm	6	\N
116	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Đèn	6	\N
117	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Ngoài trời & Sân vườn	6	\N
118	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Đồ dùng phòng tắm	6	\N
119	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Vật phẩm thờ cúng	6	\N
120	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Đồ trang trí tiệc	6	\N
121	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Chăm sóc nhà cửa và giặt ủi	6	\N
122	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Sắp xếp nhà cửa	6	\N
123	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Dụng cụ pha chế	6	\N
124	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Tinh dầu thơm phòng	6	\N
125	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Đồ dùng phòng ăn	6	\N
126	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Đồng Hồ Nam	7	\N
127	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Đồng Hồ Nữ	7	\N
128	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Bộ Đồng Hồ & Đồng Hồ Cặp	7	\N
129	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Đồng Hồ Trẻ Em	7	\N
130	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Phụ Kiện Đồng Hồ	7	\N
131	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Khác	7	\N
132	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Nhẫn	8	\N
133	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Bông tai	8	\N
134	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Khăn choàng	8	\N
135	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Găng tay	8	\N
136	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Phụ kiện tóc	8	\N
137	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Vòng tay & Lắc tay	8	\N
138	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Lắc chân	8	\N
139	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Mũ	8	\N
140	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Dây chuyền	8	\N
141	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Kính mắt	8	\N
142	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Kim loại quý	8	\N
143	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Thắt lưng	8	\N
144	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Cà vạt & Nơ cổ	8	\N
145	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Phụ kiện thêm	8	\N
146	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Bộ phụ kiện	8	\N
147	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Khác	8	\N
148	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Vớ/Tất	8	\N
149	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Ô/Dù	8	\N
150	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Ba Lô Nam	9	\N
151	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Ba Lô Laptop Nam	9	\N
152	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Túi & Cặp Đựng Laptop	9	\N
153	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Túi Chống Sốc Laptop Nam	9	\N
154	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Túi Tote Nam	9	\N
155	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Cặp Xách Công Sở Nam	9	\N
156	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Ví Cầm Tay Nam	9	\N
157	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Túi Đeo Hông & Túi Đeo Ngực Nam	9	\N
158	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Túi Đeo Chéo Nam	9	\N
159	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Bóp/Ví Nam	9	\N
160	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Khác	9	\N
161	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Máy Tính Bàn	10	\N
162	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Màn Hình	10	\N
163	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Linh Kiện Máy Tính	10	\N
164	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Thiết Bị Lưu Trữ	10	\N
165	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Thiết Bị Mạng	10	\N
166	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Máy In, Máy Scan & Máy Chiếu	10	\N
167	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Phụ Kiện Máy Tính	10	\N
168	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Laptop	10	\N
169	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Khác	10	\N
170	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Gaming	10	\N
171	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Bốt	11	\N
172	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Giày Thể Thao/Sneaker	11	\N
173	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Giày Đế Bằng	11	\N
174	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Giày Cao Gót	11	\N
175	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Giày Đế Xuồng	11	\N
176	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Xăng-đan Và Dép	11	\N
177	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Phụ Kiện Giày	11	\N
178	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Giày Khác	11	\N
179	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Vali	12	\N
180	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Túi du lịch	12	\N
181	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Phụ kiện du lịch	12	\N
182	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Dụng Cụ Thể Thao & Dã Ngoại	12	\N
183	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Giày Thể Thao	12	\N
184	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Thời Trang Thể Thao & Dã Ngoại	12	\N
185	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Phụ Kiện Thể Thao & Dã Ngoại	12	\N
186	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Khác	12	\N
187	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Trang phục bé trai	13	\N
188	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Trang phục bé gái	13	\N
189	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Giày dép bé trai	13	\N
190	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Giày dép bé gái	13	\N
191	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Khác	13	\N
192	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Quần Áo em bé	13	\N
193	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Giày tập đi & Tất sơ sinh	13	\N
194	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Phụ kiện trẻ em	13	\N
195	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Dụng cụ cầm tay	14	\N
196	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Dụng cụ điện và thiết bị lớn	14	\N
197	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Thiết bị mạch điện	14	\N
198	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Vật liệu xây dựng	14	\N
199	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Thiết bị và phụ kiện xây dựng	14	\N
200	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Chăm sóc da mặt	15	\N
201	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Tắm & chăm sóc cở thể	15	\N
202	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Trang điểm	15	\N
203	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Chăm sóc tóc	15	\N
204	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Dụng cụ & Phụ kiện Làm đẹp	15	\N
205	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Vệ sinh răng miệng	15	\N
206	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Nước hoa	15	\N
207	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Chăm sóc nam giới	15	\N
208	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Khác	15	\N
209	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Chăm sóc phụ nữ	15	\N
210	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Bộ sản phẩm làm đẹp	15	\N
211	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Bốt	16	\N
212	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Giày Thể Thao/Sneaker	16	\N
213	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Giày Sục	16	\N
214	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Giày Tây Lười	16	\N
215	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Giày Oxfords & Giày Buộc Dây	16	\N
216	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Xăng-đan và Dép	16	\N
217	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Phụ kiện giày dép	16	\N
218	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Khác	16	\N
219	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Đồ ăn vặt	17	\N
220	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Đồ chế biến sẵn	17	\N
221	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Nhu yếu phẩm	17	\N
222	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Nguyên liệu nấu ăn	17	\N
223	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Đồ làm bánh	17	\N
224	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Sữa - trứng	17	\N
225	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Đồ uống	17	\N
226	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Ngũ cốc & mứt	17	\N
227	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Các loại bánh	17	\N
228	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Đồ uống có cồn	17	\N
229	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Bộ quà tặng	17	\N
230	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Thực phẩm tươi sống và thực phẩm đông lạnh	17	\N
231	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Khác	17	\N
232	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Sở thích & Sưu tầm	18	\N
233	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Đồ chơi giải trí	18	\N
234	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Đồ chơi giáo dục	18	\N
235	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Đồ chiow cho trẻ sơ sinh & trẻ nhỏ	18	\N
236	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Đồ chơi vận động & ngoài trời	18	\N
237	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Búp bê & Đồ chơi nhồi bông	18	\N
238	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	 Máy ảnh - Máy quay phim	19	\N
239	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Camera giám sát & Camera hệ thống	19	\N
240	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Thẻ nhớ	19	\N
241	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Ống kính	19	\N
242	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Phụ kiện máy ảnh	19	\N
243	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Máy bay camera & Phụ kiện	19	\N
244	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Ba Lô Nữ	20	\N
245	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Cặp Laptop	20	\N
246	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Ví Dự Tiệc & Ví Cầm Tay	20	\N
247	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Túi Đeo Hông & Túi Đeo Ngực	20	\N
248	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Túi Tote	20	\N
249	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Túi Quai Xách	20	\N
250	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Túi Đeo Chéo & Túi Đeo Vai	20	\N
251	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Ví/Bóp Nữ	20	\N
252	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Phụ Kiện Túi	20	\N
253	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Khác	20	\N
254	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Xe đạp, xe điện	21	\N
255	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Mô tô, xe máy	21	\N
256	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Xe Ô tô	21	\N
257	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Mũ bảo hiểm	21	\N
258	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Phụ kiện xe máy	21	\N
259	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Phụ kiện xe đạp	21	\N
260	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Phụ kiện bên trong ô tô	21	\N
261	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Dầu nhớt & dầu nhờn	21	\N
262	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Phụ tùng ô tô	21	\N
263	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Phụ tùng xe máy	21	\N
264	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Phụ kiện bên ngoài ô tô	21	\N
265	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Chăm sóc ô tô	21	\N
266	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Dịch vụ cho xe	21	\N
267	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Giặt giũ & Chăm sóc nhà cửa	22	\N
268	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Giấy vệ sinh, khăn giấy	22	\N
269	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Vệ sinh nhà cửa	22	\N
270	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Vệ sinh bát đĩa	22	\N
271	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Dụng cụ vệ sinh	22	\N
272	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Chát khử mùi, làm thơm	22	\N
273	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Thuốc diệt côn trùng	22	\N
274	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Túi, màng bọc thực phẩm	22	\N
275	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Bao bì, túi đựng rác	22	\N
276	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Vật tư y tế	23	\N
277	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Chống muỗi & xua đuổi con trùng	23	\N
278	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Thực phẩm chức năng	23	\N
279	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Tã người lớn	23	\N
280	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Hỗ trợ làm đẹp	23	\N
281	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Hỗ trợ tình dục	23	\N
282	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Dụng cụ massage và trị liệu	23	\N
283	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Khác	23	\N
284	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Đồ gia dụng nhà bếp	24	\N
285	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Đồ gia dụng lớn	24	\N
286	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Máy hút bụi & Thiết bị làm sạch	24	\N
287	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Quạt & Máy nóng lạnh	24	\N
288	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Thiết bị chăm sóc quần áo	24	\N
289	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Khác	24	\N
290	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Máy xay, ép, máy đánh trứng trộn bột, máy ,xay thực phẩm	24	\N
291	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Bếp điện	24	\N
292	2025-06-30 12:00:00	1	1	2025-06-30 12:00:00	t	N/A	\N	Sách Tiếng Việt	25	\N
293	2025-07-01 12:00:00	1	1	2025-07-01 12:00:00	t	N/A	\N	Sách ngoại văn	25	\N
294	2025-07-02 12:00:00	1	1	2025-07-02 12:00:00	t	N/A	\N	Gói Quà	25	\N
295	2025-07-03 12:00:00	1	1	2025-07-03 12:00:00	t	N/A	\N	Bút viết	25	\N
296	2025-07-04 12:00:00	1	1	2025-07-04 12:00:00	t	N/A	\N	Dụng cụ học sinh & văn phòng	25	\N
297	2025-07-05 12:00:00	1	1	2025-07-05 12:00:00	t	N/A	\N	Màu, Họa Cụ và Đồ Thủ Công	25	\N
298	2025-07-06 12:00:00	1	1	2025-07-06 12:00:00	t	N/A	\N	Sổ và Giấy Các Loại	25	\N
299	2025-07-07 12:00:00	1	1	2025-07-07 12:00:00	t	N/A	\N	Quà Lưu Niệm	25	\N
300	2025-07-08 12:00:00	1	1	2025-07-08 12:00:00	t	N/A	\N	Nhạc cụ và phụ kiện âm nhạc	25	\N
301	2025-07-09 12:00:00	1	1	2025-07-09 12:00:00	t	N/A	\N	Thức ăn cho thú cưng	26	\N
302	2025-07-10 12:00:00	1	1	2025-07-10 12:00:00	t	N/A	\N	Phụ kiện cho thú cưng	26	\N
303	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Vệ sinh cho thú cưng	26	\N
304	2025-06-15 12:00:00	1	1	2025-06-15 12:00:00	t	N/A	\N	Quần áo thú cưng	26	\N
305	2025-06-16 12:00:00	1	1	2025-06-16 12:00:00	t	N/A	\N	Chăm sóc sức khỏe	26	\N
306	2025-06-17 12:00:00	1	1	2025-06-17 12:00:00	t	N/A	\N	Làm đẹp cho thú cưng	26	\N
307	2025-06-18 12:00:00	1	1	2025-06-18 12:00:00	t	N/A	\N	Khác	26	\N
308	2025-06-19 12:00:00	1	1	2025-06-19 12:00:00	t	N/A	\N	Nhà hàng & Ăn uống	27	\N
309	2025-06-20 12:00:00	1	1	2025-06-20 12:00:00	t	N/A	\N	Sự kiện & Giải trí	27	\N
310	2025-06-21 12:00:00	1	1	2025-06-21 12:00:00	t	N/A	\N	Nạp tiền tài khoản	27	\N
311	2025-06-22 12:00:00	1	1	2025-06-22 12:00:00	t	N/A	\N	Sức khỏe & Làm đẹp	27	\N
312	2025-06-23 12:00:00	1	1	2025-06-23 12:00:00	t	N/A	\N	Gọi xe 	27	\N
313	2025-06-24 12:00:00	1	1	2025-06-24 12:00:00	t	N/A	\N	Khóa học	27	\N
314	2025-06-25 12:00:00	1	1	2025-06-25 12:00:00	t	N/A	\N	Du lịch & Khách sạn	27	\N
315	2025-06-26 12:00:00	1	1	2025-06-26 12:00:00	t	N/A	\N	Mua sắm	27	\N
316	2025-06-27 12:00:00	1	1	2025-06-27 12:00:00	t	N/A	\N	Mã quà tặng Shoppe	27	\N
317	2025-06-28 12:00:00	1	1	2025-06-28 12:00:00	t	N/A	\N	Thanh toán hóa đơn	27	\N
318	2025-06-29 12:00:00	1	1	2025-06-29 12:00:00	t	N/A	\N	Dịch vụ khác	27	\N
\.


--
-- TOC entry 3741 (class 0 OID 18677)
-- Dependencies: 228
-- Data for Name: chat_messages; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.chat_messages (id, is_read, message, receiver_id, sender_id, sent_at) FROM stdin;
\.


--
-- TOC entry 3743 (class 0 OID 18685)
-- Dependencies: 230
-- Data for Name: coupons; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.coupons (id, created_at, created_by, last_modified_by, last_modified_on, active, code, discount_percent, expiry_date, usage_limit, valid_from, valid_to) FROM stdin;
\.


--
-- TOC entry 3745 (class 0 OID 18695)
-- Dependencies: 232
-- Data for Name: currency_rates; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.currency_rates (id, created_at, created_by, last_modified_by, last_modified_on, from_currency, rate, to_currency) FROM stdin;
1	2025-08-01 16:17:22.391879	\N	\N	2025-08-01 16:17:22.391928	USD	26131.00	VND
2	2025-08-01 16:17:22.433782	\N	\N	2025-08-01 16:17:22.433794	USD	150.40	JPY
3	2025-08-01 16:17:22.460554	\N	\N	2025-08-01 16:17:22.460567	VND	0.00	USD
4	2025-08-01 16:17:22.467642	\N	\N	2025-08-01 16:17:22.467661	JPY	0.01	USD
\.


--
-- TOC entry 3747 (class 0 OID 18707)
-- Dependencies: 234
-- Data for Name: login_history; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.login_history (id, created_at, created_by, last_modified_by, last_modified_on, ip_address, location, login_at, success, user_agent, user_id) FROM stdin;
\.


--
-- TOC entry 3749 (class 0 OID 18717)
-- Dependencies: 236
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.notifications (id, created_at, created_by, last_modified_by, last_modified_on, description, email, icon_color_hex, icon_name, is_read, "time", title, type) FROM stdin;
\.


--
-- TOC entry 3750 (class 0 OID 18730)
-- Dependencies: 237
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.order_items (id, order_id, product_id, product_image, product_name, quantity, total_price, unit_price) FROM stdin;
\.


--
-- TOC entry 3752 (class 0 OID 18738)
-- Dependencies: 239
-- Data for Name: order_status_logs; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.order_status_logs (id, created_at, created_by, last_modified_by, last_modified_on, order_id, status) FROM stdin;
\.


--
-- TOC entry 3754 (class 0 OID 18748)
-- Dependencies: 241
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.orders (id, created_at, created_by, last_modified_by, last_modified_on, address_id, coupon_id, delivered_at, discount_amount, estimated_delivery, notes, order_number, payment_status, shipping_fee, shipping_method_id, shipping_status, status, subtotal, tax_amount, total_amount, user_id) FROM stdin;
\.


--
-- TOC entry 3756 (class 0 OID 18761)
-- Dependencies: 243
-- Data for Name: otps; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.otps (id, created_at, created_by, last_modified_by, last_modified_on, email, expired_at, is_expired, is_used, otp) FROM stdin;
\.


--
-- TOC entry 3758 (class 0 OID 18771)
-- Dependencies: 245
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.payments (id, created_at, created_by, last_modified_by, last_modified_on, amount, description, order_id, paid, paid_at, payment_method, payment_method_id, status, transaction_id) FROM stdin;
\.


--
-- TOC entry 3760 (class 0 OID 18783)
-- Dependencies: 247
-- Data for Name: product_images; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.product_images (id, created_at, created_by, last_modified_by, last_modified_on, image_url, is_primary, product_id) FROM stdin;
\.


--
-- TOC entry 3762 (class 0 OID 18793)
-- Dependencies: 249
-- Data for Name: product_reviews; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.product_reviews (id, created_at, created_by, last_modified_by, last_modified_on, comment, product_id, rating, user_id) FROM stdin;
\.


--
-- TOC entry 3764 (class 0 OID 18803)
-- Dependencies: 251
-- Data for Name: product_variants; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.product_variants (id, created_at, created_by, last_modified_by, last_modified_on, price_adjustment, product_id, stock, variant_name) FROM stdin;
\.


--
-- TOC entry 3766 (class 0 OID 18813)
-- Dependencies: 253
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.products (id, created_at, created_by, last_modified_by, last_modified_on, active, category_id, description, dimensions, featured, image_url, name, price, rating, review_count, shop_id, sku, sold_count, status, stock, weight) FROM stdin;
1	2025-08-01 16:17:22.531011	\N	\N	2025-08-01 16:17:22.531024	t	1	Latest smartphone with advanced features	15x7x1 cm	t	https://example.com/images/smartphone-x.jpg	Smartphone X	799.99	0	0	0	ELEC-SP-001	0	ACTIVE	50	0.2
2	2025-08-01 16:17:22.535465	\N	\N	2025-08-01 16:17:22.53548	t	1	High-performance laptop for professionals	35x25x2 cm	t	https://example.com/images/laptop-pro.jpg	Laptop Pro	1299.99	0	0	0	ELEC-LP-002	0	ACTIVE	30	2
3	2025-08-01 16:17:22.539434	\N	\N	2025-08-01 16:17:22.53945	t	1	Premium wireless earbuds with noise cancellation	5x5x3 cm	f	https://example.com/images/wireless-earbuds.jpg	Wireless Earbuds	149.99	0	0	0	ELEC-WE-003	0	ACTIVE	100	0.05
4	2025-08-01 16:17:22.543079	\N	\N	2025-08-01 16:17:22.543097	t	2	Comfortable cotton casual shirt for men	30x20x2 cm	f	https://example.com/images/mens-shirt.jpg	Men's Casual Shirt	39.99	0	0	0	CLOTH-MS-001	0	ACTIVE	200	0.3
5	2025-08-01 16:17:22.5455	\N	\N	2025-08-01 16:17:22.545509	t	2	Elegant dress for women	40x30x2 cm	t	https://example.com/images/womens-dress.jpg	Women's Dress	59.99	0	0	0	CLOTH-WD-002	0	ACTIVE	150	0.4
6	2025-08-01 16:17:22.54782	\N	\N	2025-08-01 16:17:22.547834	t	3	Automatic coffee maker with timer	25x20x30 cm	f	https://example.com/images/coffee-maker.jpg	Coffee Maker	89.99	0	0	0	HOME-CM-001	0	ACTIVE	75	3
7	2025-08-01 16:17:22.551127	\N	\N	2025-08-01 16:17:22.551142	t	3	High-speed blender for smoothies and more	20x15x35 cm	f	https://example.com/images/blender.jpg	Blender	69.99	0	0	0	HOME-BL-002	0	ACTIVE	60	2.5
8	2025-08-01 16:17:22.553532	\N	\N	2025-08-01 16:17:22.553544	t	4	Bestselling fiction novel	20x15x3 cm	f	https://example.com/images/great-novel.jpg	The Great Novel	14.99	0	0	0	BOOK-GN-001	0	ACTIVE	300	0.5
9	2025-08-01 16:17:22.562993	\N	\N	2025-08-01 16:17:22.56301	t	4	Comprehensive cookbook for all skill levels	25x20x2 cm	t	https://example.com/images/cookbook.jpg	Cooking Masterclass	24.99	0	0	0	BOOK-CM-002	0	ACTIVE	150	0.8
10	2025-08-01 16:17:22.567473	\N	\N	2025-08-01 16:17:22.567507	t	5	Gentle facial cleanser for all skin types	10x5x15 cm	f	https://example.com/images/facial-cleanser.jpg	Facial Cleanser	19.99	0	0	0	BEAUTY-FC-001	0	ACTIVE	200	0.3
11	2025-08-01 16:17:22.57053	\N	\N	2025-08-01 16:17:22.570543	t	5	Premium fragrance for special occasions	8x8x15 cm	t	https://example.com/images/perfume.jpg	Luxury Perfume	79.99	0	0	0	BEAUTY-LP-002	0	ACTIVE	50	0.2
\.


--
-- TOC entry 3768 (class 0 OID 18824)
-- Dependencies: 255
-- Data for Name: shipping_methods; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.shipping_methods (id, created_at, created_by, last_modified_by, last_modified_on, active, cost, estimated_days, name) FROM stdin;
1	2025-08-01 16:17:22.95206	\N	\N	2025-08-01 16:17:22.952067	t	5.99	5	Standard Shipping
2	2025-08-01 16:17:22.95413	\N	\N	2025-08-01 16:17:22.954137	t	15.99	2	Express Shipping
3	2025-08-01 16:17:22.956753	\N	\N	2025-08-01 16:17:22.956885	t	25.99	1	Next Day Delivery
\.


--
-- TOC entry 3770 (class 0 OID 18834)
-- Dependencies: 257
-- Data for Name: shop_notifications; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.shop_notifications (id, created_at, created_by, last_modified_by, last_modified_on, content, is_read, shop_id, type) FROM stdin;
\.


--
-- TOC entry 3771 (class 0 OID 18843)
-- Dependencies: 258
-- Data for Name: social_accounts; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.social_accounts (id, created_at, created_by, last_modified_by, last_modified_on, email, name, provider_name, user_id) FROM stdin;
\.


--
-- TOC entry 3772 (class 0 OID 18853)
-- Dependencies: 259
-- Data for Name: token; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.token (id, created_at, created_by, last_modified_by, last_modified_on, expiration_date, expired, is_mobile, refresh_expiration_date, refresh_token, revoked, token, token_type, user_id) FROM stdin;
\.


--
-- TOC entry 3774 (class 0 OID 18863)
-- Dependencies: 261
-- Data for Name: user_addresses; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_addresses (id, address, is_default, name_of_user, phone_number, user_id) FROM stdin;
\.


--
-- TOC entry 3776 (class 0 OID 18871)
-- Dependencies: 263
-- Data for Name: user_device_tokens; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_device_tokens (id, created_at, created_by, last_modified_by, last_modified_on, device_id, device_name, email, fcm_token, platform) FROM stdin;
\.


--
-- TOC entry 3778 (class 0 OID 18881)
-- Dependencies: 265
-- Data for Name: user_notifications; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_notifications (id, created_at, created_by, last_modified_by, last_modified_on, content, is_read, type, user_id) FROM stdin;
\.


--
-- TOC entry 3780 (class 0 OID 18891)
-- Dependencies: 267
-- Data for Name: user_settings; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_settings (id, created_at, created_by, last_modified_by, last_modified_on, dark_mode, login_alerts, email_master_enabled, email_order, email_promo, email_survey, sms_master_enabled, sms_promo, zalo_master_enabled, zalo_promo, request_disable_account, two_fa_enabled, user_id) FROM stdin;
1	2025-08-01 16:17:22.727077	\N	\N	2025-08-01 16:17:22.727087	f	t	t	t	t	t	t	f	t	t	f	f	1
2	2025-08-01 16:17:22.737221	\N	\N	2025-08-01 16:17:22.73723	f	t	t	t	t	t	t	f	t	t	f	f	2
3	2025-08-01 16:17:22.746579	\N	\N	2025-08-01 16:17:22.746603	f	t	t	t	t	t	t	f	t	t	f	f	3
4	2025-08-01 16:17:22.75255	\N	\N	2025-08-01 16:17:22.752559	f	t	t	t	t	t	t	f	t	t	f	f	4
5	2025-08-01 16:17:22.758159	\N	\N	2025-08-01 16:17:22.758169	f	t	t	t	t	t	t	f	t	t	f	f	5
6	2025-08-01 16:17:22.764264	\N	\N	2025-08-01 16:17:22.764272	f	t	t	t	t	t	t	f	t	t	f	f	6
7	2025-08-01 16:17:22.770773	\N	\N	2025-08-01 16:17:22.770781	f	t	t	t	t	t	t	f	t	t	f	f	7
\.


--
-- TOC entry 3782 (class 0 OID 18901)
-- Dependencies: 269
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.users (id, created_at, created_by, last_modified_by, last_modified_on, avatar, cart_id, date_of_birth, email, gender, password, name, phone, preferred_currency, preferred_language, role, status, totp_secret, username, wallet_id, user_settings_id) FROM stdin;
1	2025-08-01 16:17:22.681185	\N	\N	2025-08-01 16:17:22.913606		cart-ad@gmail.com		ad@gmail.com	1	$2a$10$a.FTfRqiqlHqCV3TsLMPiehruIhE3kzHanuilkkix9OycR4FCW94i	Admin User	+84987654321	USD	en	3	1			wallet-ad@gmail.com	1
2	2025-08-01 16:17:22.685251	\N	\N	2025-08-01 16:17:22.92572		cart-cus@gmail.com		cus@gmail.com	1	$2a$10$a.FTfRqiqlHqCV3TsLMPiehruIhE3kzHanuilkkix9OycR4FCW94i	New User	+84123456789	USD	en	0	1			wallet-cus@gmail.com	2
3	2025-08-01 16:17:22.688006	\N	\N	2025-08-01 16:17:22.92803		cart-st@gmail.com		st@gmail.com	1	$2a$10$a.FTfRqiqlHqCV3TsLMPiehruIhE3kzHanuilkkix9OycR4FCW94i	STAFF User	+84123456789	USD	en	2	1			wallet-st@gmail.com	3
4	2025-08-01 16:17:22.691068	\N	\N	2025-08-01 16:17:22.929963		cart-sp@gmail.com		sp@gmail.com	1	$2a$10$a.FTfRqiqlHqCV3TsLMPiehruIhE3kzHanuilkkix9OycR4FCW94i	SHOP User	+84123456789	USD	en	1	1			wallet-sp@gmail.com	4
5	2025-08-01 16:17:22.697905	\N	\N	2025-08-01 16:17:22.932072		cart-sp2@gmail.com		sp2@gmail.com	1	$2a$10$a.FTfRqiqlHqCV3TsLMPiehruIhE3kzHanuilkkix9OycR4FCW94i	SHOP User 2	+84123456789	USD	en	1	3			wallet-sp2@gmail.com	5
6	2025-08-01 16:17:22.699963	\N	\N	2025-08-01 16:17:22.933712		cart-manager@gmail.com		manager@gmail.com	1	$2a$10$a.FTfRqiqlHqCV3TsLMPiehruIhE3kzHanuilkkix9OycR4FCW94i	MANAGER User	+84123456789	USD	en	4	1			wallet-manager@gmail.com	6
7	2025-08-01 16:17:22.705191	\N	\N	2025-08-01 16:17:22.941404		cart-blocked@gmail.com		blocked@gmail.com	1	$2a$10$a.FTfRqiqlHqCV3TsLMPiehruIhE3kzHanuilkkix9OycR4FCW94i	Blocked User	+84123456789	USD	en	0	2			wallet-blocked@gmail.com	7
\.


--
-- TOC entry 3784 (class 0 OID 18914)
-- Dependencies: 271
-- Data for Name: wallet_transactions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.wallet_transactions (id, created_at, created_by, last_modified_by, last_modified_on, amount, completed_at, currency, description, reference_id, status, transaction_id, type, wallet_id) FROM stdin;
1	2025-08-01 16:17:23.372073	\N	\N	2025-08-01 16:17:23.372086	1000.00	\N	USD	Initial deposit for admin	\N	0	544fdf1a-235d-4eab-be5f-3aabed7f775b	DEPOSIT	1
2	2025-08-01 16:17:23.379759	\N	\N	2025-08-01 16:17:23.379766	1000.00	2025-08-01 16:17:23.378793	USD	Initial deposit for admin	\N	1	544fdf1a-235d-4eab-be5f-3aabed7f775b	DEPOSIT	1
3	2025-08-01 16:17:23.430391	\N	\N	2025-08-01 16:17:23.430398	500.00	\N	USD	Initial deposit for user	\N	0	25750215-1b78-4acb-9b76-a1ffe612e906	DEPOSIT	2
4	2025-08-01 16:17:23.437817	\N	\N	2025-08-01 16:17:23.43783	500.00	2025-08-01 16:17:23.437013	USD	Initial deposit for user	\N	1	25750215-1b78-4acb-9b76-a1ffe612e906	DEPOSIT	2
5	2025-08-01 16:17:23.480953	\N	\N	2025-08-01 16:17:23.480959	300.00	\N	USD	Initial deposit for staff user	\N	0	db613a31-0f54-4251-9e27-d429771a4b25	DEPOSIT	3
6	2025-08-01 16:17:23.483472	\N	\N	2025-08-01 16:17:23.48348	300.00	2025-08-01 16:17:23.482831	USD	Initial deposit for staff user	\N	1	db613a31-0f54-4251-9e27-d429771a4b25	DEPOSIT	3
7	2025-08-01 16:17:23.525805	\N	\N	2025-08-01 16:17:23.525811	200.00	\N	USD	Initial deposit for shop user	\N	0	81d79f2f-5f83-464f-8f40-07c56deb97f5	DEPOSIT	4
8	2025-08-01 16:17:23.531543	\N	\N	2025-08-01 16:17:23.531551	200.00	2025-08-01 16:17:23.530908	USD	Initial deposit for shop user	\N	1	81d79f2f-5f83-464f-8f40-07c56deb97f5	DEPOSIT	4
9	2025-08-01 16:17:23.572363	\N	\N	2025-08-01 16:17:23.572377	150.00	\N	USD	Initial deposit for shop user 2	\N	0	c8d229aa-80ab-43c1-b599-ee6f0300247d	DEPOSIT	5
10	2025-08-01 16:17:23.574957	\N	\N	2025-08-01 16:17:23.574964	150.00	2025-08-01 16:17:23.574426	USD	Initial deposit for shop user 2	\N	1	c8d229aa-80ab-43c1-b599-ee6f0300247d	DEPOSIT	5
11	2025-08-01 16:17:23.625828	\N	\N	2025-08-01 16:17:23.625855	800.00	\N	USD	Initial deposit for manager user	\N	0	b2f1fb26-29a8-4ad0-bbc7-cd8c73aa9d77	DEPOSIT	6
12	2025-08-01 16:17:23.630294	\N	\N	2025-08-01 16:17:23.630305	800.00	2025-08-01 16:17:23.628789	USD	Initial deposit for manager user	\N	1	b2f1fb26-29a8-4ad0-bbc7-cd8c73aa9d77	DEPOSIT	6
\.


--
-- TOC entry 3786 (class 0 OID 18926)
-- Dependencies: 273
-- Data for Name: wallets; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.wallets (id, created_at, created_by, last_modified_by, last_modified_on, active, balance, currency, wallet_id, user_id) FROM stdin;
1	2025-08-01 16:17:23.29697	\N	\N	2025-08-01 16:17:23.393247	t	1000.00	USD	wallet-ad@gmail.com	1
2	2025-08-01 16:17:23.40762	\N	\N	2025-08-01 16:17:23.453579	t	500.00	USD	wallet-cus@gmail.com	2
3	2025-08-01 16:17:23.464257	\N	\N	2025-08-01 16:17:23.487347	t	300.00	USD	wallet-st@gmail.com	3
4	2025-08-01 16:17:23.500132	\N	\N	2025-08-01 16:17:23.541425	t	200.00	USD	wallet-sp@gmail.com	4
5	2025-08-01 16:17:23.555124	\N	\N	2025-08-01 16:17:23.578764	t	150.00	USD	wallet-sp2@gmail.com	5
6	2025-08-01 16:17:23.595314	\N	\N	2025-08-01 16:17:23.634868	t	800.00	USD	wallet-manager@gmail.com	6
\.


--
-- TOC entry 3788 (class 0 OID 18936)
-- Dependencies: 275
-- Data for Name: wishlists; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.wishlists (id, created_at, created_by, last_modified_by, last_modified_on, product_id, user_id) FROM stdin;
\.


--
-- TOC entry 3796 (class 0 OID 0)
-- Dependencies: 215
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.addresses_id_seq', 1, false);


--
-- TOC entry 3797 (class 0 OID 0)
-- Dependencies: 217
-- Name: admin_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.admin_settings_id_seq', 11, true);


--
-- TOC entry 3798 (class 0 OID 0)
-- Dependencies: 219
-- Name: api_quotas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.api_quotas_id_seq', 1, false);


--
-- TOC entry 3799 (class 0 OID 0)
-- Dependencies: 221
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 1, false);


--
-- TOC entry 3800 (class 0 OID 0)
-- Dependencies: 223
-- Name: carts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.carts_id_seq', 1, false);


--
-- TOC entry 3801 (class 0 OID 0)
-- Dependencies: 225
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.categories_id_seq', 318, true);


--
-- TOC entry 3802 (class 0 OID 0)
-- Dependencies: 227
-- Name: chat_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.chat_messages_id_seq', 1, false);


--
-- TOC entry 3803 (class 0 OID 0)
-- Dependencies: 229
-- Name: coupons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.coupons_id_seq', 1, false);


--
-- TOC entry 3804 (class 0 OID 0)
-- Dependencies: 231
-- Name: currency_rates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.currency_rates_id_seq', 4, true);


--
-- TOC entry 3805 (class 0 OID 0)
-- Dependencies: 233
-- Name: login_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.login_history_id_seq', 1, false);


--
-- TOC entry 3806 (class 0 OID 0)
-- Dependencies: 235
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.notifications_id_seq', 1, false);


--
-- TOC entry 3807 (class 0 OID 0)
-- Dependencies: 276
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.order_items_id_seq', 1, false);


--
-- TOC entry 3808 (class 0 OID 0)
-- Dependencies: 238
-- Name: order_status_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.order_status_logs_id_seq', 1, false);


--
-- TOC entry 3809 (class 0 OID 0)
-- Dependencies: 240
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.orders_id_seq', 1, false);


--
-- TOC entry 3810 (class 0 OID 0)
-- Dependencies: 242
-- Name: otps_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.otps_id_seq', 1, false);


--
-- TOC entry 3811 (class 0 OID 0)
-- Dependencies: 244
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.payments_id_seq', 1, false);


--
-- TOC entry 3812 (class 0 OID 0)
-- Dependencies: 246
-- Name: product_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.product_images_id_seq', 1, false);


--
-- TOC entry 3813 (class 0 OID 0)
-- Dependencies: 248
-- Name: product_reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.product_reviews_id_seq', 1, false);


--
-- TOC entry 3814 (class 0 OID 0)
-- Dependencies: 250
-- Name: product_variants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.product_variants_id_seq', 1, false);


--
-- TOC entry 3815 (class 0 OID 0)
-- Dependencies: 252
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.products_id_seq', 11, true);


--
-- TOC entry 3816 (class 0 OID 0)
-- Dependencies: 254
-- Name: shipping_methods_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.shipping_methods_id_seq', 3, true);


--
-- TOC entry 3817 (class 0 OID 0)
-- Dependencies: 256
-- Name: shop_notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.shop_notifications_id_seq', 1, false);


--
-- TOC entry 3818 (class 0 OID 0)
-- Dependencies: 277
-- Name: social_accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.social_accounts_id_seq', 1, false);


--
-- TOC entry 3819 (class 0 OID 0)
-- Dependencies: 260
-- Name: user_addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_addresses_id_seq', 1, false);


--
-- TOC entry 3820 (class 0 OID 0)
-- Dependencies: 262
-- Name: user_device_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_device_tokens_id_seq', 1, false);


--
-- TOC entry 3821 (class 0 OID 0)
-- Dependencies: 264
-- Name: user_notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_notifications_id_seq', 1, false);


--
-- TOC entry 3822 (class 0 OID 0)
-- Dependencies: 266
-- Name: user_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_settings_id_seq', 7, true);


--
-- TOC entry 3823 (class 0 OID 0)
-- Dependencies: 268
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- TOC entry 3824 (class 0 OID 0)
-- Dependencies: 270
-- Name: wallet_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.wallet_transactions_id_seq', 12, true);


--
-- TOC entry 3825 (class 0 OID 0)
-- Dependencies: 272
-- Name: wallets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.wallets_id_seq', 6, true);


--
-- TOC entry 3826 (class 0 OID 0)
-- Dependencies: 274
-- Name: wishlists_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.wishlists_id_seq', 1, false);


--
-- TOC entry 3491 (class 2606 OID 18633)
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 3493 (class 2606 OID 18643)
-- Name: admin_settings admin_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.admin_settings
    ADD CONSTRAINT admin_settings_pkey PRIMARY KEY (id);


--
-- TOC entry 3495 (class 2606 OID 18649)
-- Name: api_quotas api_quotas_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.api_quotas
    ADD CONSTRAINT api_quotas_pkey PRIMARY KEY (id);


--
-- TOC entry 3497 (class 2606 OID 18655)
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3499 (class 2606 OID 18665)
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- TOC entry 3501 (class 2606 OID 18675)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3503 (class 2606 OID 18683)
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 3505 (class 2606 OID 18693)
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- TOC entry 3507 (class 2606 OID 18705)
-- Name: currency_rates currency_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.currency_rates
    ADD CONSTRAINT currency_rates_pkey PRIMARY KEY (id);


--
-- TOC entry 3509 (class 2606 OID 18715)
-- Name: login_history login_history_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.login_history
    ADD CONSTRAINT login_history_pkey PRIMARY KEY (id);


--
-- TOC entry 3511 (class 2606 OID 18729)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 3513 (class 2606 OID 18736)
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3515 (class 2606 OID 18746)
-- Name: order_status_logs order_status_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_status_logs
    ADD CONSTRAINT order_status_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 3517 (class 2606 OID 18759)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 3521 (class 2606 OID 18769)
-- Name: otps otps_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.otps
    ADD CONSTRAINT otps_pkey PRIMARY KEY (id);


--
-- TOC entry 3523 (class 2606 OID 18781)
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- TOC entry 3525 (class 2606 OID 18791)
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- TOC entry 3527 (class 2606 OID 18801)
-- Name: product_reviews product_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_reviews
    ADD CONSTRAINT product_reviews_pkey PRIMARY KEY (id);


--
-- TOC entry 3529 (class 2606 OID 18811)
-- Name: product_variants product_variants_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT product_variants_pkey PRIMARY KEY (id);


--
-- TOC entry 3531 (class 2606 OID 18822)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3533 (class 2606 OID 18832)
-- Name: shipping_methods shipping_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.shipping_methods
    ADD CONSTRAINT shipping_methods_pkey PRIMARY KEY (id);


--
-- TOC entry 3535 (class 2606 OID 18842)
-- Name: shop_notifications shop_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.shop_notifications
    ADD CONSTRAINT shop_notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 3537 (class 2606 OID 18852)
-- Name: social_accounts social_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 3539 (class 2606 OID 18861)
-- Name: token token_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_pkey PRIMARY KEY (id);


--
-- TOC entry 3561 (class 2606 OID 18956)
-- Name: wallets uk3x8uve6j94tgub04634ujx5p8; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT uk3x8uve6j94tgub04634ujx5p8 UNIQUE (wallet_id);


--
-- TOC entry 3549 (class 2606 OID 18950)
-- Name: user_settings uk4bos7satl9xeqd18frfeqg6tt; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT uk4bos7satl9xeqd18frfeqg6tt UNIQUE (user_id);


--
-- TOC entry 3553 (class 2606 OID 18952)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 3543 (class 2606 OID 18948)
-- Name: user_device_tokens uk8m3wt56wj3c1osfh3wo3mah7f; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_device_tokens
    ADD CONSTRAINT uk8m3wt56wj3c1osfh3wo3mah7f UNIQUE (fcm_token);


--
-- TOC entry 3555 (class 2606 OID 18954)
-- Name: users ukkkgur0mp2rb80vdk050f40cu7; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukkkgur0mp2rb80vdk050f40cu7 UNIQUE (user_settings_id);


--
-- TOC entry 3519 (class 2606 OID 18946)
-- Name: orders uknthkiu7pgmnqnu86i2jyoe2v7; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uknthkiu7pgmnqnu86i2jyoe2v7 UNIQUE (order_number);


--
-- TOC entry 3563 (class 2606 OID 18958)
-- Name: wallets uksswfdl9fq40xlkove1y5kc7kv; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT uksswfdl9fq40xlkove1y5kc7kv UNIQUE (user_id);


--
-- TOC entry 3541 (class 2606 OID 18869)
-- Name: user_addresses user_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_addresses
    ADD CONSTRAINT user_addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 3545 (class 2606 OID 18879)
-- Name: user_device_tokens user_device_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_device_tokens
    ADD CONSTRAINT user_device_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 3547 (class 2606 OID 18889)
-- Name: user_notifications user_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT user_notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 3551 (class 2606 OID 18899)
-- Name: user_settings user_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_pkey PRIMARY KEY (id);


--
-- TOC entry 3557 (class 2606 OID 18912)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3559 (class 2606 OID 18924)
-- Name: wallet_transactions wallet_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 3565 (class 2606 OID 18934)
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (id);


--
-- TOC entry 3567 (class 2606 OID 18944)
-- Name: wishlists wishlists_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT wishlists_pkey PRIMARY KEY (id);


--
-- TOC entry 3568 (class 2606 OID 18966)
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 3571 (class 2606 OID 18976)
-- Name: login_history fk20v0mimmdegh2afs39uixlxpm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.login_history
    ADD CONSTRAINT fk20v0mimmdegh2afs39uixlxpm FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3574 (class 2606 OID 19006)
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3579 (class 2606 OID 19016)
-- Name: social_accounts fk6rmxxiton5yuvu7ph2hcq2xn7; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT fk6rmxxiton5yuvu7ph2hcq2xn7 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3575 (class 2606 OID 19001)
-- Name: orders fk6y8524wxp1t96w22s03w455gh; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk6y8524wxp1t96w22s03w455gh FOREIGN KEY (shipping_method_id) REFERENCES public.shipping_methods(id);


--
-- TOC entry 3583 (class 2606 OID 19036)
-- Name: wallet_transactions fk8seu7b87ifqi09ghhssusmb0x; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT fk8seu7b87ifqi09ghhssusmb0x FOREIGN KEY (wallet_id) REFERENCES public.wallets(id);


--
-- TOC entry 3570 (class 2606 OID 18971)
-- Name: carts fkb5o626f86h46m4s7ms6ginnop; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3572 (class 2606 OID 18981)
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- TOC entry 3584 (class 2606 OID 19041)
-- Name: wallets fkc1foyisidw7wqqrkamafuwn4e; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT fkc1foyisidw7wqqrkamafuwn4e FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3576 (class 2606 OID 18991)
-- Name: orders fkhlglkvf5i60dv6dn397ethgpt; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkhlglkvf5i60dv6dn397ethgpt FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- TOC entry 3580 (class 2606 OID 19021)
-- Name: token fkj8rfw4x0wjjyibfqq566j4qng; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT fkj8rfw4x0wjjyibfqq566j4qng FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3577 (class 2606 OID 18996)
-- Name: orders fkn1d1gkxckw648m2n2d5gx0yx5; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkn1d1gkxckw648m2n2d5gx0yx5 FOREIGN KEY (coupon_id) REFERENCES public.coupons(id);


--
-- TOC entry 3581 (class 2606 OID 19026)
-- Name: user_addresses fkn2fisxyyu3l9wlch3ve2nocgp; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_addresses
    ADD CONSTRAINT fkn2fisxyyu3l9wlch3ve2nocgp FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3573 (class 2606 OID 18986)
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 3578 (class 2606 OID 19011)
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- TOC entry 3569 (class 2606 OID 18961)
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- TOC entry 3582 (class 2606 OID 19031)
-- Name: users fkt275ghj5s7h3i4sm7r4uhrmbo; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkt275ghj5s7h3i4sm7r4uhrmbo FOREIGN KEY (user_settings_id) REFERENCES public.user_settings(id);


-- Completed on 2025-08-01 09:50:15 UTC

--
-- PostgreSQL database dump complete
--

